### ISSUE TITLE
Android crash when receive notification from Firebase console with sound

### ISSUE THREAD

**Issue by AndresRR-IG** [CrossGeeks/PushNotificationPlugin#13]
Hi,

I am getting this crash when send a notification with parameters and sound from the firebase console.

```
[AndroidRuntime] Parameter name: length
[AndroidRuntime]   at System.String.Substring (System.Int32 startIndex, System.Int32 length) [0x0004a] in <85f7b553f08f43a8a65ed84e5bc4a8ce>:0 
[AndroidRuntime]   at Plugin.PushNotification.DefaultPushNotificationHandler.OnReceived (System.Collections.Generic.IDictionary`2[TKey,TValue] parameters) [0x00201] in <7bfb079c05ee4ace8e60f5228d71d2db>:0 
[AndroidRuntime]   at Plugin.PushNotification.PNMessagingService.OnMessageReceived (Firebase.Messaging.RemoteMessage message) [0x001e1] in <7bfb079c05ee4ace8e60f5228d71d2db>:0 
[AndroidRuntime]   at Firebase.Messaging.FirebaseMessagingService.n_OnMessageReceived_Lcom_google_firebase_messaging_RemoteMessage_ (System.IntPtr jnienv, System.IntPtr native__this, System.IntPtr native_message) [0x00011] in <9d0d1f3bc0ed4aa895271e840e47dc1a>:0 
[AndroidRuntime]   at (wrapper dynamic-method) System.Object:5fe8cbfb-18dd-4ec9-b81b-d93389c12952 (intptr,intptr,intptr)
[AndroidRuntime] 	at md573c9264e488c62a04468d109fbc8adb8.PNMessagingService.n_onMessageReceived(Native Method)
[AndroidRuntime] 	at md573c9264e488c62a04468d109fbc8adb8.PNMessagingService.onMessageReceived(PNMessagingService.java:29)
[AndroidRuntime] 	at com.google.firebase.messaging.FirebaseMessagingService.zzl(Unknown Source)
[AndroidRuntime] 	at com.google.firebase.messaging.FirebaseMessagingService.zzJ(Unknown Source)
[AndroidRuntime] 	at com.google.firebase.messaging.FirebaseMessagingService.handleIntent(Unknown Source)
[AndroidRuntime] 	at com.google.firebase.iid.zzb$1.run(Unknown Source)
[AndroidRuntime] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
[AndroidRuntime] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
[AndroidRuntime] 	at java.lang.Thread.run(Thread.java:761)
```

Regards,

Andrés R.

**Comment by rdelrosario** [comment]
What payload are you sending and nuget version using?

**Comment by rdelrosario** [comment]
Also without sound parameter it doesn't crash?

**Comment by AndresRR-IG** [comment]
We sent a default firebase console message with two extra string parameters. 

I tried it with versions 1.1.0 and 1.1.1.

It only crash with sound parameter (turn on the switch in the console)

**Comment by rdelrosario** [comment]
what's the name of the sound you are sending?

**Comment by AndresRR-IG** [comment]
I can't capture the payload right now. But i don't put any name, only turn on the switch in the console(is a valid option -works fine in iOS).

**Comment by rdelrosario** [comment]
Should be fixed on latest release

**Comment by alsraonani** [comment]
Is it about  com.google.firebase:firebase-messaging:17.3.0
Can you confirm latest release?
