### ISSUE TITLE
Crash for Android Device in China Region 

### ISSUE THREAD

**Issue by pawanshakya** [CrossGeeks/PushNotificationPlugin#132]
Hi, 
Recently I have **upgraded my nugget from Version="1.2.6"  to Version="3.0.25".** 
Earlier version in China region was not breaking, though token was coming as empty and obviously push was not working for them. 

But it looks like with new update some parsing logic for token broke which lead to breaking for Chinese devices. 

Explicitly added check for IsGooglePlayServicesAvailable as well but still same issue. 

if (IsGooglePlayServicesAvailable)
            {
                //If debug you should reset the token each time.
                #if DEBUG
                PushNotificationManager.Initialize(this, true);
                #else
                PushNotificationManager.Initialize(this,false);
                #endif
                ...........
}

**Below is exception  -** 
----------------------------------------------------------------------------------------
com.google.android.gms.tasks.RuntimeExecutionException: java.io.IOException: SERVICE_NOT_AVAILABLE
	at com.google.android.gms.tasks.zzu.getResult(Unknown Source:15)
	at md53da296b4b9f7aa6e187dc28cf9fd28f3.PushNotificationManager.n_onComplete(Native Method)
	at md53da296b4b9f7aa6e187dc28cf9fd28f3.PushNotificationManager.onComplete(PushNotificationManager.java:30)
	at com.google.android.gms.tasks.zzj.run(Unknown Source:4)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:227)
	at android.app.ActivityThread.main(ActivityThread.java:7533)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:953)
	Caused by: java.io.IOException: SERVICE_NOT_AVAILABLE
	at com.google.firebase.iid.zzr.zza(Unknown Source:67)
	at com.google.firebase.iid.zzr.zza(Unknown Source:80)
	at com.google.firebase.iid.zzu.then(Unknown Source:4)
	at com.google.android.gms.tasks.zzd.run(Unknown Source:5)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:919)

**Comment by rdelrosario** [comment]
Please try the latest version

**Comment by pawanshakya** [comment]
Sure, will give that a try.
However bit curious to insights, did any specific change made from 3.0.25 (using currently) to 3.1.1(latest) which might fix this?

**Comment by rdelrosario** [comment]
Yes that fix and other improvements

**Comment by rdelrosario** [comment]
Such as large icon support, set default channel importance and a few other
improvements.

**Comment by pawanshakya** [comment]
> Please try the latest version

Sure, will give that a try.. 

However bit curious to know about change made in package in regards to this issue ( from 3.0.25 (currently using) to 3.1.1(latest) ) which might have fix this ?
